name: Run Circuit Simulations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install ngspice and gnuplot
        run: |
          sudo apt-get update
          sudo apt-get install -y ngspice gnuplot

      - name: Run simulation and generate plot
        run: |
          # Run ngspice in batch mode (assuming your circuit file is src/inverter.spice)
          ngspice -b src/inverter.spice

          # Create gnuplot script to generate plot.png
          echo "
          set terminal png size 800,600
          set output 'plot.png'
          set title 'Inverter Output Voltage'
          set xlabel 'Time (s)'
          set ylabel 'V(OUT)'
          plot 'voltages.dat' using 2:1 with lines title 'V(OUT)'
          " > plot.gp

          # Run gnuplot to produce plot.png
          gnuplot plot.gp

      - name: Upload output logs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: simulation-outputs
          path: output.log

      - name: Upload plot image
        uses: actions/upload-artifact@v4.6.2
        with:
          name: simulation-plot
          path: plot1.png
