name: Run Circuit Simulations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ngspice gnuplot

      - name: Run simulation
        run: |
          # Run your ngspice simulation (replace with your actual command)
          ngspice -b src/inverter.spice

      - name: Generate plot with gnuplot
        run: |
          # Create the plot
          gnuplot -e "
            set terminal png size 800,600;
            set output 'plot1.png';
            set title 'V(IN) vs V(OUT)';
            set xlabel 'V(IN) (V)';
            set ylabel 'V(OUT) (V)';
            plot 'voltages.dat' using 1:2 with lines lw 2;"
          
      - name: List files to verify plot creation
        run: ls -l

      - name: Upload plot artifact if exists
        if: ${{ exists('plot1.png') }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: plot1
          path: plot1.png
